In [2]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.array([1,2,3,4])
arr1


array([1, 2, 3, 4])

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
df = pd.DataFrame()
x = df.values
type(x)


numpy.ndarray

основные способы задание разных матриц 

In [7]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[3, 2, 9],
       [0, 5, 5],
       [4, 2, 0]])

In [8]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [12]:
np.random.randint(0, 5, 3)

array([1, 3, 2])

In [15]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [34]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array


array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [100]:
my_array[:-1]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [147]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [32]:
sum(big_secret[:,-1])

3154.332495807108

Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [87]:
big_secret[0:5, 0:5]
sum_first_diagonal = sum(big_secret[i][i] for i in range(len(big_secret)))
sum_first_diagonal

121.37188663699624

In [55]:
-len(big_secret)

-5

Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [115]:
# big_secret[0:5,-1:-5] 
# big_secret[:-5]
big_secret[0:5,:-6:-1] 

# np.diagonal(a)

array([[ 294.        ,  490.        ,  686.        ,  276.        ,
         460.        ],
       [  33.1662479 ,   33.13608305,   33.10589071,   33.07567082,
          33.04542328],
       [2500.        , 2401.        , 2304.        , 2209.        ,
        2116.        ],
       [  33.1662479 ,   33.13608305,   33.10589071,   33.07567082,
          33.04542328],
       [ 294.        ,  490.        ,  686.        ,  276.        ,
         460.        ]])

In [118]:
a = np.diagonal(big_secret[0:5,:-6:-1])
a

array([ 294.        ,   33.13608305, 2304.        ,   33.07567082,
        460.        ])

In [120]:
np.prod(np.diagonal(big_secret[0:5,:-6:-1]))

341505315559.2347

In [165]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [166]:
big_secret[0::2, 0::2]  = -1
big_secret[1::2, 1::2] = 1 

Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [170]:
np.diag(big_secret[:,0:5]).sum()


-1.0

Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [171]:
np.prod(np.diagonal(big_secret[0:5,:-6:-1]))

-1.0

In [ ]:

Функция	Описание
abs	Абсолютное значение целых, вещественных или комплексных элементов массива
sqrt	Квадратный корень каждого элемента массива
exp	Экспонента (ex) каждого элемента массива
log, log10, log2, log1p	Натуральный (по основанию е), десятичный, двоичный логарифм и функция log(1+x) соответственно
modf	Дробные и целые части массива в виде отдельных массивов
isnan	Массив логических (булевых) значений, показывающий, какие из элементов исходного массива  являются NaN (не числами)
cos, sin, tan	Обычные тригонометрические функции
arccos, arcsin, arctan	Обратные тригонометрические функции

У нас есть два массива: найдём их сумму, разность, произведение, частное и умножим один из массивов на число:

In [172]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [4]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[4, 4, 7, 7],
       [0, 9, 0, 0],
       [3, 4, 9, 9]])

In [5]:
my_array<5

array([[ True,  True, False, False],
       [ True, False,  True,  True],
       [ True,  True, False, False]])

In [6]:
my_array[my_array<5]

array([4, 4, 0, 0, 0, 3, 4])

In [8]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[4, 7],
       [0, 0],
       [3, 9]])

In [9]:
my_array = np.random.randint(0, 10, (4, 6))

In [11]:
np.sort(my_array, axis=1)

array([[2, 3, 3, 4, 6, 9],
       [2, 3, 4, 4, 7, 8],
       [0, 3, 5, 5, 5, 8],
       [1, 1, 2, 2, 7, 9]])

In [12]:
np.sort(my_array, axis=0)

array([[2, 1, 2, 1, 2, 0],
       [3, 4, 3, 2, 3, 3],
       [4, 5, 5, 4, 6, 7],
       [7, 9, 9, 5, 8, 8]])

In [16]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [ ]:
# great_secret

Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [18]:
sum(np.cos(great_secret[0]))

0.16006721889793019

Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [20]:
sum(great_secret[great_secret > 50])

5470.0

Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [35]:
great_secret.flatten()


array([ 0.        ,  4.64158883, 66.66666667,  1.        ,  4.65700951,
       40.        ,  1.41421356,  4.67232873, 67.33333333,  1.73205081,
        4.68754815, 40.4       ,  2.        ,  4.70266938, 68.        ,
        2.23606798,  4.71769398, 40.8       ,  2.44948974,  4.73262349,
       68.66666667,  2.64575131,  4.7474594 , 41.2       ,  2.82842712,
        4.76220316, 69.33333333,  3.        ,  4.77685618, 41.6       ,
        3.16227766,  4.79141986, 70.        ,  3.31662479,  4.80589553,
       42.        ,  3.46410162,  4.82028453, 70.66666667,  3.60555128,
        4.83458813, 42.4       ,  3.74165739,  4.84880759, 71.33333333,
        3.87298335,  4.86294413, 42.8       ,  4.        ,  4.87699896,
       72.        ,  4.12310563,  4.89097325, 43.2       ,  4.24264069,
        4.90486813, 72.66666667,  4.35889894,  4.91868473, 43.6       ,
        4.47213595,  4.93242415, 73.33333333,  4.58257569,  4.94608744,
       44.        ,  4.69041576,  4.95967566, 74.        ,  4.79

In [36]:
great_secret[150]

IndexError: index 150 is out of bounds for axis 0 with size 100

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [33]:
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [34]:
np.sort(great_secret, axis = 0)
sum(great_secret[-1])
# great_secret[-1]

75.3881468318802

In [56]:
arr1 = np.array([1,2,3,4])
# students = np.array([[1,2,3,4,5,6,7,8,9,10],[135,160,163,147,138,149,136,154,137,165],
#                      [34,43,40,44,41,54,39,48,35,60], [4,5,4.3,5,4.7,3.9,4.2,4.9,3.7,4.6]])
students = np.array([[1,135,34,4],[2,160,43,5],[3,163,40,4.3],[4,147,44,5],[5,138,41,4.7],[6,149,54,3.9],
                     [7,136,39,4.2],[8,154,48,4.9],[9,137,35,3.7],[10,165,60,4.6]])
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [59]:
median = np.median(students[:,-2])
median


42.0

In [60]:
mean = np.mean(students[:,-1])
mean


4.430000000000001

In [62]:
mean - median

-37.57

In [64]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [68]:
std = np.std(students[:,-2])
std ** 2

60.36

In [71]:
np.random.randint(1, 10, (10, 10))

array([[4, 9, 1, 5, 4, 8, 9, 1, 6, 6],
       [2, 4, 3, 5, 3, 2, 7, 4, 8, 3],
       [3, 3, 1, 4, 3, 1, 8, 7, 9, 6],
       [6, 4, 4, 7, 4, 7, 5, 2, 5, 9],
       [3, 3, 8, 4, 3, 5, 3, 7, 6, 4],
       [7, 1, 4, 3, 9, 4, 3, 3, 7, 5],
       [9, 2, 3, 9, 6, 3, 2, 8, 1, 5],
       [1, 6, 8, 6, 7, 8, 6, 4, 3, 9],
       [1, 3, 8, 1, 8, 5, 7, 7, 4, 6],
       [1, 4, 3, 4, 7, 8, 7, 2, 4, 1]])

Перед вами массив my_array, созданный с помощью кода выше. Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

Код должен содержать имя массива и набор индексов для получения нужного среза. В ответе использовать только положительные значения индексов и введите ответ в одну строку без пробелов.

In [73]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])


In [98]:
# my_slice = my_array[1:1,1:2,1:3,2:1]
my_slice = my_array[1:4,1:4]
my_slice[:] = 0
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16,  0,  0,  0, 20],
       [21, 22, 23, 24, 25]])

Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [101]:
sum(np.sin(my_array))
my_array.flatten()
sin = np.sin(my_array)
sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.        ,  0.        ,  0.        , -0.54402111],
       [-0.99999021,  0.        ,  0.        ,  0.        ,  0.65028784],
       [-0.28790332,  0.        ,  0.        ,  0.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [102]:
my_slicee[:] = sin[1:4,1:4]
my_slicee[:] = 0
sin

NameError: name 'my_slicee' is not defined

# Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [103]:
# bigdata = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
bigdata = [x**2 for x in range(100,1000) if x%2 != 0]
bigdata

[10201,
 10609,
 11025,
 11449,
 11881,
 12321,
 12769,
 13225,
 13689,
 14161,
 14641,
 15129,
 15625,
 16129,
 16641,
 17161,
 17689,
 18225,
 18769,
 19321,
 19881,
 20449,
 21025,
 21609,
 22201,
 22801,
 23409,
 24025,
 24649,
 25281,
 25921,
 26569,
 27225,
 27889,
 28561,
 29241,
 29929,
 30625,
 31329,
 32041,
 32761,
 33489,
 34225,
 34969,
 35721,
 36481,
 37249,
 38025,
 38809,
 39601,
 40401,
 41209,
 42025,
 42849,
 43681,
 44521,
 45369,
 46225,
 47089,
 47961,
 48841,
 49729,
 50625,
 51529,
 52441,
 53361,
 54289,
 55225,
 56169,
 57121,
 58081,
 59049,
 60025,
 61009,
 62001,
 63001,
 64009,
 65025,
 66049,
 67081,
 68121,
 69169,
 70225,
 71289,
 72361,
 73441,
 74529,
 75625,
 76729,
 77841,
 78961,
 80089,
 81225,
 82369,
 83521,
 84681,
 85849,
 87025,
 88209,
 89401,
 90601,
 91809,
 93025,
 94249,
 95481,
 96721,
 97969,
 99225,
 100489,
 101761,
 103041,
 104329,
 105625,
 106929,
 108241,
 109561,
 110889,
 112225,
 113569,
 114921,
 116281,
 117649,
 119025,
 

In [107]:
median = np.median(bigdata)
median

302501.0

Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых

In [109]:
std = np.std(bigdata)
std

292095.0301991155

Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [110]:
corr = np.corrcoef(bigdata[0::2], bigdata[1::2])
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])