In [5]:
import numpy as np
import pandas as pd

In [3]:
arr1 = np.array([1,2,3,4])
arr1


array([1, 2, 3, 4])

In [4]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
df = pd.DataFrame()
x = df.values
type(x)


numpy.ndarray

основные способы задание разных матриц 

In [7]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[3, 2, 9],
       [0, 5, 5],
       [4, 2, 0]])

In [8]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [12]:
np.random.randint(0, 5, 3)

array([1, 3, 2])