In [47]:
import numpy as np
import pandas as pd
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2], float)
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00])

In [5]:
share_living_space = apartment[1]/apartment[0]

In [11]:
share_living_space

0.5277310924369748

In [12]:
apartment = np.delete(apartment, [0, 1])

In [16]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [29]:
apartment = np.append(apartment, share_living_space)
apartment

array([5.95000000e+01, 3.14000000e+01, 1.90000000e+01, 2.20000000e+01,
       6.05500000e+04, 2.00000000e+00, 5.27731092e-01, 5.27731092e-01,
       5.27731092e-01])

Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.

In [36]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t.mean()
t.min()


12

In [45]:
hus = np.array([120,150,90])
wife = np.array([130,130,130])
mom = np.array([2, 3, 2.5])
euro = 72

hus + wife + (mom * euro)

array([394., 496., 400.])

In [49]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [53]:
x = Hut_Paradise_DF.values
x

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

Найдите вектор параметров квартиры номер 5:

In [60]:
y = x[4]
y

array([40, 33,  1,  6, 20, 16], dtype=int64)

Найдите вектор этажей всех квартир

In [63]:
y = x[:,3]
y

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

На каком этаже расположена квартира номер 3?

In [65]:
y = x[2,3]
y

10

Найдите количество квартир

In [68]:
len(x)

9

Вычислите вектор нежилой площади:

In [71]:
x[:,1] - x[:,5]


array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны

In [75]:
x[:,0] / 10 * 4


array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели

In [84]:
time=np.array([10,20,30,15,5,40,20,8,20])
# print(np.dot(x[:,4],time))
print(x[:,4]@time)

1348


роверьте, являются ли векторы попарно ортогональными.

In [91]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('(u,v):',np.dot(u,v))
print('(v,w):',np.dot(v,w))
print('(w,u):',np.dot(w,u))

(u,v): 0
(v,w): 0
(w,u): 0


Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [94]:
app = (2 * v) + (-3 * w)
app

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [96]:
np.dot(app,u)

0

In [98]:
# нормировка
# a_norm=a/np.linalg.norm(a)
# print('a_norm:',a_norm)
# print('length of a_norm:',np.linalg.norm(a_norm))

In [105]:
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)
# u_norm
# v_norm 
w_norm

array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143])

In [145]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [146]:
Husband_Income = np.reshape(Husband_Income, (3,1))
Wife_Income = np.reshape(Wife_Income, (3,1))
Mother_In_Law_Income = np.reshape(Mother_In_Law_Income, (3,1))

lnc = np.c_[Husband_Income, Wife_Income, Mother_In_Law_Income] 
lnc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [147]:
Husband_Сonsumption = np.reshape(Husband_Сonsumption, (3,1))
Wife_Сonsumption = np.reshape(Wife_Сonsumption, (3,1))
Mother_In_Law_Сonsumption = np.reshape(Mother_In_Law_Сonsumption, (3,1))

Cons = np.c_[Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption] 
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [151]:
lnc - Cons

array([[ 50,  50, -10],
       [170, 120,  60],
       [ 80, -10, -40]])

In [160]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

Найдите произведение матрицы  А и вектора х в том порядке, в котором их можно умножить.

In [165]:
A@x

array([26, 30])

In [174]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
A, B

(array([[1, 9, 8, 5],
        [3, 6, 3, 2],
        [3, 3, 3, 3],
        [0, 2, 5, 9],
        [4, 4, 1, 2]]),
 array([[ 1, -1,  0,  1,  1],
        [-2,  0,  2, -1,  1]]))

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

In [177]:
B@A


array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [178]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Найдите матрицу Грама системы векторов 

In [182]:
A=np.array([x,y,z])
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [183]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [189]:
Count_DF, Price_DF

(       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                 10                5           12       15    10
 Борис                2               21            3       25     6
 Вика                12               12            0       30     4
 Галя                 4                8           18       14     5
 Дима                 6               25           27       25    18
 Егор                10                3            2       17    12
 Женя                22                1            4       25    20
 Юра                  7                0           31       31    28,
        Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                2.0              1.5          1.0      0.8   1.0
 Борис              1.8              2.5          1.0      1.0   1.0
 Вика               2.0              2.0          0.0      0.5   2.0
 Галя               1.8              1.2          2.8      0.8   2.0
 Дима               2.5          

In [187]:
Count = Count_DF.values
Count

Price = Price_DF.values
Price

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

Найдите вектор выручки Бориса.

In [193]:
Count[1] * Price[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [201]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
(Count * Price ) @ com
# salon_inc = (P*C)@(com)

# print(salon_inc)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Найдите вектор прибыли стилистов.

In [211]:
Count * Price @ (np.ones(5)-com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])