In [47]:
import numpy as np
import pandas as pd
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2], float)
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00])

In [5]:
share_living_space = apartment[1]/apartment[0]

In [11]:
share_living_space

0.5277310924369748

In [12]:
apartment = np.delete(apartment, [0, 1])

In [16]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [29]:
apartment = np.append(apartment, share_living_space)
apartment

array([5.95000000e+01, 3.14000000e+01, 1.90000000e+01, 2.20000000e+01,
       6.05500000e+04, 2.00000000e+00, 5.27731092e-01, 5.27731092e-01,
       5.27731092e-01])

Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.

In [36]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t.mean()
t.min()


12

In [45]:
hus = np.array([120,150,90])
wife = np.array([130,130,130])
mom = np.array([2, 3, 2.5])
euro = 72

hus + wife + (mom * euro)

array([394., 496., 400.])

In [49]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [53]:
x = Hut_Paradise_DF.values
x

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

Найдите вектор параметров квартиры номер 5:

In [60]:
y = x[4]
y

array([40, 33,  1,  6, 20, 16], dtype=int64)

Найдите вектор этажей всех квартир

In [63]:
y = x[:,3]
y

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

На каком этаже расположена квартира номер 3?

In [65]:
y = x[2,3]
y

10

Найдите количество квартир

In [68]:
len(x)

9

Вычислите вектор нежилой площади:

In [71]:
x[:,1] - x[:,5]


array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны

In [75]:
x[:,0] / 10 * 4


array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели

In [84]:
time=np.array([10,20,30,15,5,40,20,8,20])
# print(np.dot(x[:,4],time))
print(x[:,4]@time)

1348


роверьте, являются ли векторы попарно ортогональными.

In [91]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('(u,v):',np.dot(u,v))
print('(v,w):',np.dot(v,w))
print('(w,u):',np.dot(w,u))

(u,v): 0
(v,w): 0
(w,u): 0


Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [94]:
app = (2 * v) + (-3 * w)
app

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [96]:
np.dot(app,u)

0

In [98]:
# нормировка
# a_norm=a/np.linalg.norm(a)
# print('a_norm:',a_norm)
# print('length of a_norm:',np.linalg.norm(a_norm))

In [104]:
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)
# u_norm
# v_norm 
w_norm

array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143])