In [47]:
import numpy as np
import pandas as pd
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2], float)
apartment

array([5.950e+01, 3.140e+01, 1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00])

In [5]:
share_living_space = apartment[1]/apartment[0]

In [11]:
share_living_space

0.5277310924369748

In [12]:
apartment = np.delete(apartment, [0, 1])

In [16]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [29]:
apartment = np.append(apartment, share_living_space)
apartment

array([5.95000000e+01, 3.14000000e+01, 1.90000000e+01, 2.20000000e+01,
       6.05500000e+04, 2.00000000e+00, 5.27731092e-01, 5.27731092e-01,
       5.27731092e-01])

Введите значение получившегося нового признака share_living_space. Используйте код и ссылки на документацию из описания квартиры.

In [36]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t.mean()
t.min()


12

In [45]:
hus = np.array([120,150,90])
wife = np.array([130,130,130])
mom = np.array([2, 3, 2.5])
euro = 72

hus + wife + (mom * euro)

array([394., 496., 400.])

In [49]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [53]:
x = Hut_Paradise_DF.values
x

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

Найдите вектор параметров квартиры номер 5:

In [60]:
y = x[4]
y

array([40, 33,  1,  6, 20, 16], dtype=int64)

Найдите вектор этажей всех квартир

In [63]:
y = x[:,3]
y

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

На каком этаже расположена квартира номер 3?

In [65]:
y = x[2,3]
y

10

Найдите количество квартир

In [68]:
len(x)

9

Вычислите вектор нежилой площади:

In [71]:
x[:,1] - x[:,5]


array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны

In [75]:
x[:,0] / 10 * 4


array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели

In [84]:
time=np.array([10,20,30,15,5,40,20,8,20])
# print(np.dot(x[:,4],time))
print(x[:,4]@time)

1348


роверьте, являются ли векторы попарно ортогональными.

In [91]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

print('(u,v):',np.dot(u,v))
print('(v,w):',np.dot(v,w))
print('(w,u):',np.dot(w,u))

(u,v): 0
(v,w): 0
(w,u): 0


Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [94]:
app = (2 * v) + (-3 * w)
app

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [96]:
np.dot(app,u)

0

In [98]:
# нормировка
# a_norm=a/np.linalg.norm(a)
# print('a_norm:',a_norm)
# print('length of a_norm:',np.linalg.norm(a_norm))

In [105]:
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)
# u_norm
# v_norm 
w_norm

array([ 0.21320072, -0.85280287, -0.21320072,  0.        , -0.42640143])

In [145]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [146]:
Husband_Income = np.reshape(Husband_Income, (3,1))
Wife_Income = np.reshape(Wife_Income, (3,1))
Mother_In_Law_Income = np.reshape(Mother_In_Law_Income, (3,1))

lnc = np.c_[Husband_Income, Wife_Income, Mother_In_Law_Income] 
lnc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [147]:
Husband_Сonsumption = np.reshape(Husband_Сonsumption, (3,1))
Wife_Сonsumption = np.reshape(Wife_Сonsumption, (3,1))
Mother_In_Law_Сonsumption = np.reshape(Mother_In_Law_Сonsumption, (3,1))

Cons = np.c_[Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption] 
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [151]:
lnc - Cons

array([[ 50,  50, -10],
       [170, 120,  60],
       [ 80, -10, -40]])

In [160]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

array([[ 5, -1,  3,  1,  2],
       [-2,  8,  5, -1,  1]])

Найдите произведение матрицы  А и вектора х в том порядке, в котором их можно умножить.

In [165]:
A@x

array([26, 30])

In [174]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
A, B

(array([[1, 9, 8, 5],
        [3, 6, 3, 2],
        [3, 3, 3, 3],
        [0, 2, 5, 9],
        [4, 4, 1, 2]]),
 array([[ 1, -1,  0,  1,  1],
        [-2,  0,  2, -1,  1]]))

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

In [177]:
B@A


array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [178]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Найдите матрицу Грама системы векторов 

In [182]:
A=np.array([x,y,z])
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [183]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [189]:
Count_DF, Price_DF

(       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                 10                5           12       15    10
 Борис                2               21            3       25     6
 Вика                12               12            0       30     4
 Галя                 4                8           18       14     5
 Дима                 6               25           27       25    18
 Егор                10                3            2       17    12
 Женя                22                1            4       25    20
 Юра                  7                0           31       31    28,
        Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
 Аня                2.0              1.5          1.0      0.8   1.0
 Борис              1.8              2.5          1.0      1.0   1.0
 Вика               2.0              2.0          0.0      0.5   2.0
 Галя               1.8              1.2          2.8      0.8   2.0
 Дима               2.5          

In [187]:
Count = Count_DF.values
Count

Price = Price_DF.values
Price

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

Найдите вектор выручки Бориса.

In [193]:
Count[1] * Price[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [201]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
(Count * Price ) @ com
# salon_inc = (P*C)@(com)

# print(salon_inc)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Найдите вектор прибыли стилистов.

In [212]:
Count * Price @ (np.ones(5)-com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [215]:
A1 = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите обратную матрицу к матрице А.

In [216]:
A1_inv=np.linalg.inv(A1)
A1_inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [217]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов v1, v2, v3, v4.

In [222]:
A=np.array([v1,v2,v3,v4])
np.linalg.matrix_rank(A)

4

Найдите матрицу Грама системы векторов v1, v2, v3, v4.

In [224]:
A@A.T

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

Найдите определитель матрицы Грама системы v1, v2, v3, v4.

In [234]:
np.linalg.det(A@A.T)


3716647.9999999995

Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

In [233]:
np.linalg.inv(A@A.T)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [236]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [239]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

Составьте корреляциюнную матрицу перечисленных признаков вместе с целевой переменной, исключив столбец Serial No.

В поля для ответа впишите, округлив до двух знаков после точки:

In [264]:
# df = df.drop(columns=['Serial No.'])

C = df.corr(method = 'pearson')
C
# sns.heatmap(data=C, annot=True)

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.827200           0.635376  0.613498   
TOEFL Score         0.827200     1.000000           0.649799  0.644410   
University Rating   0.635376     0.649799           1.000000  0.728024   
SOP                 0.613498     0.644410           0.728024  1.000000   
LOR                 0.524679     0.541563           0.608651  0.663707   
CGPA                0.825878     0.810574           0.705254  0.712154   
Research            0.563398     0.467012           0.427047  0.408116   
Chance of Admit     0.810351     0.792228           0.690132  0.684137   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.541563  0.810574  0.467012          0.792228  
University Rating  0.608651  0.705254  0.427047          0.690132  
SOP                0.663707  0.712154  0.408116          0.684137  
LOR                1.000000  0.637469  0.372526          0.645365  
CGPA               0.637469  1.000000  0.501311          0.882413  
Research           0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.645365  0.882413  0.545871          1.000000

Постройте отдельно две матрицы корреляций признаков и целевой переменной: для соискателей, делавших исследования (Research=1) и для тех, у кого исследований нет (Research=0).

В каком случае признаки сильнее скоррелированы между собой?

In [263]:
dfR0 = df[df.Research == 0]
dfR0

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
4          314          103                  2  2.0   3.0  8.21         0   
7          308          101                  2  3.0   4.0  7.90         0   
8          302          102                  1  2.0   1.5  8.00         0   
9          323          108                  3  3.5   3.0  8.60         0   
15         314          105                  3  3.5   2.5  8.30         0   
..         ...          ...                ...  ...   ...   ...       ...   
487        327          115                  4  3.5   4.0  9.14         0   
489        302          110                  3  4.0   4.5  8.50         0   
491        297           99                  4  3.0   3.5  7.81         0   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit   
4                0.65  
7                0.68  
8                0.50  
9                0.45  
15               0.54  
..                ...  
487              0.79  
489              0.65  
491              0.54  
498              0.73  
499              0.84  

[220 rows x 8 columns]

In [262]:
Cr0 = dfR0.corr(method = 'pearson')
Cr0
# sns.heatmap(data=Cr0, annot=True)

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.680668           0.384715  0.371424   
TOEFL Score         0.680668     1.000000           0.495748  0.476563   
University Rating   0.384715     0.495748           1.000000  0.607496   
SOP                 0.371424     0.476563           0.607496  1.000000   
LOR                 0.365864     0.470956           0.484262  0.618680   
CGPA                0.678476     0.696774           0.516427  0.547098   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.603827     0.622458           0.428580  0.470188   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.470956  0.696774       NaN          0.622458  
University Rating  0.484262  0.516427       NaN          0.428580  
SOP                0.618680  0.547098       NaN          0.470188  
LOR                1.000000  0.562517       NaN          0.542528  
CGPA               0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.542528  0.752714       NaN          1.000000

In [254]:
Cr1 = df[df.Research == 1].corr(method = 'pearson')
Cr1

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.824170           0.614739  0.613318   
TOEFL Score         0.824170     1.000000           0.602445  0.629436   
University Rating   0.614739     0.602445           1.000000  0.723126   
SOP                 0.613318     0.629436           0.723126  1.000000   
LOR                 0.443374     0.436199           0.573881  0.591858   
CGPA                0.806720     0.784173           0.692237  0.717750   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.802439     0.787180           0.713094  0.708238   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.436199  0.784173       NaN          0.787180  
University Rating  0.573881  0.692237       NaN          0.713094  
SOP                0.591858  0.717750       NaN          0.708238  
LOR                1.000000  0.564794       NaN          0.588558  
CGPA               0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.588558  0.892489       NaN          1.000000